DROP TABLE PERSON;

CREATE TABLE PERSON (
    ID int NOT NULL PRIMARY KEY,
    FIRSTNAME varchar(255),
    AGE  int,
);

INSERT INTO PERSON(ID, FIRSTNAME, AGE) VALUES (101, 'person1',  21);

INSERT INTO PERSON(ID, FIRSTNAME, AGE) VALUES (102, 'person2', 21);
